// Generates renderer/src/rpc/contracts.d.ts from the Sqlm.Contracts assembly by reflection, so
// the TypeScript side of the RPC bridge cannot drift from the C# JobEvent union (PLAN.md §4.2,
// §12: "a stale checked-in contracts.d.ts fails the build"). Run via `dotnet run --project
// tools/Sqlm.ContractsGen -- <output-path>`; Sqlm.Contracts.csproj wires this in as a post-build
// step, and CI diffs the result against what's checked in.

using System.Reflection;
using System.Text;
using System.Text.Json.Serialization;
using Sqlm.Contracts;

if (args.Length != 1)
{
    Console.Error.WriteLine("usage: Sqlm.ContractsGen <output-path>");
    return 1;
}

var outputPath = args[0];
var assembly = typeof(JobEvent).Assembly;
var sb = new StringBuilder();

sb.AppendLine("// AUTO-GENERATED by tools/Sqlm.ContractsGen from Sqlm.Contracts. Do not edit by hand —");
sb.AppendLine("// run `dotnet run --project tools/Sqlm.ContractsGen -- <output-path>` to regenerate.");
sb.AppendLine();

var publicTypes = assembly.GetExportedTypes()
    .Where(t => !t.IsGenericTypeDefinition && !(t.IsAbstract && t.IsSealed)) // drop static classes, e.g. SqlmJsonOptions
    .OrderBy(t => t.Name, StringComparer.Ordinal)
    .ToList();

var nullability = new NullabilityInfoContext();

foreach (var type in publicTypes)
{
    if (type.IsEnum)
    {
        EmitEnum(sb, type);
    }
    else if (type.GetCustomAttribute<JsonPolymorphicAttribute>() is not null)
    {
        EmitUnionAlias(sb, type);
    }
    else if (type.IsClass || (type.IsValueType && !type.IsPrimitive))
    {
        EmitInterface(sb, type, nullability);
    }
}

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outputPath))!);
File.WriteAllText(outputPath, sb.ToString());
Console.WriteLine($"wrote {outputPath}");
return 0;

static void EmitEnum(StringBuilder sb, Type enumType)
{
    var members = Enum.GetNames(enumType).Select(ToCamelCase);
    sb.AppendLine($"export type {enumType.Name} = {string.Join(" | ", members.Select(m => $"\"{m}\""))};");
    sb.AppendLine();
}

static void EmitUnionAlias(StringBuilder sb, Type baseType)
{
    var derived = baseType.GetCustomAttributes<JsonDerivedTypeAttribute>()
        .Select(a => a.DerivedType.Name);
    sb.AppendLine($"export type {baseType.Name} = {string.Join(" | ", derived)};");
    sb.AppendLine();
}

static void EmitInterface(StringBuilder sb, Type type, NullabilityInfoContext nullability)
{
    var discriminator = FindDiscriminatorValue(type);

    sb.AppendLine($"export interface {type.Name} {{");
    if (discriminator is not null)
    {
        sb.AppendLine($"  kind: \"{discriminator}\";");
    }

    foreach (var property in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
    {
        if (property.Name == "EqualityContract")
        {
            continue;
        }

        sb.AppendLine($"  {ToCamelCase(property.Name)}: {MapPropertyType(property, nullability)};");
    }

    sb.AppendLine("}");
    sb.AppendLine();
}

static string? FindDiscriminatorValue(Type type)
{
    for (var baseType = type.BaseType; baseType is not null; baseType = baseType.BaseType)
    {
        var match = baseType.GetCustomAttributes<JsonDerivedTypeAttribute>()
            .FirstOrDefault(a => a.DerivedType == type);
        if (match is not null)
        {
            return (string)match.TypeDiscriminator!;
        }
    }

    return null;
}

static string MapPropertyType(PropertyInfo property, NullabilityInfoContext nullability)
{
    var mapped = MapType(property.PropertyType);

    // Nullable<T> value types are handled inside MapType via Nullable.GetUnderlyingType; nullable
    // *reference* types (e.g. `string?`) only show up as metadata, not as a distinct runtime Type,
    // so they need NullabilityInfoContext instead.
    if (!property.PropertyType.IsValueType && nullability.Create(property).WriteState == NullabilityState.Nullable)
    {
        return $"{mapped} | null";
    }

    return mapped;
}

static string MapType(Type type)
{
    if (Nullable.GetUnderlyingType(type) is { } underlying)
    {
        return $"{MapType(underlying)} | null";
    }

    if (type == typeof(string) || type == typeof(Guid) || type == typeof(DateTime) ||
        type == typeof(DateTimeOffset) || type == typeof(TimeSpan))
    {
        return "string";
    }

    if (type == typeof(bool))
    {
        return "boolean";
    }

    if (type == typeof(int) || type == typeof(long) || type == typeof(short) ||
        type == typeof(double) || type == typeof(float) || type == typeof(decimal))
    {
        return "number";
    }

    if (type == typeof(object) || type.FullName == "System.Text.Json.JsonElement")
    {
        return "unknown";
    }

    if (type.IsEnum)
    {
        return type.Name;
    }

    if (type.IsGenericType)
    {
        var definition = type.GetGenericTypeDefinition();
        var typeArguments = type.GetGenericArguments();

        if (definition == typeof(IReadOnlyList<>) || definition == typeof(IReadOnlyCollection<>) ||
            definition == typeof(List<>) || definition == typeof(IEnumerable<>))
        {
            return $"{MapType(typeArguments[0])}[]";
        }

        if (definition == typeof(IReadOnlyDictionary<,>) || definition == typeof(Dictionary<,>))
        {
            return $"Record<string, {MapType(typeArguments[1])}>";
        }
    }

    if (type.IsArray)
    {
        return $"{MapType(type.GetElementType()!)}[]";
    }

    // A reference to another generated interface/enum/union alias.
    return type.Name;
}

static string ToCamelCase(string pascalCase) =>
    pascalCase.Length == 0 ? pascalCase : char.ToLowerInvariant(pascalCase[0]) + pascalCase[1..];
