// AUTO-GENERATED by tools/Sqlm.ContractsGen from Sqlm.Contracts. Do not edit by hand —
// run `dotnet run --project tools/Sqlm.ContractsGen -- <output-path>` to regenerate.

export interface DoneEvent {
  kind: "done";
  summary: RunSummary;
}

export interface FailedEvent {
  kind: "failed";
  error: SerializedError;
  resumeToken: string | null;
}

export type JobEvent = PhaseEvent | TableEvent | LogEvent | WarningEvent | DoneEvent | FailedEvent;

export interface LogEvent {
  kind: "log";
  level: LogLevel;
  message: string;
  context: unknown | null;
}

export type LogLevel = "trace" | "debug" | "information" | "warning" | "error";

export type Phase = "introspect" | "plan" | "ddl" | "copy" | "index" | "workflow" | "verify" | "finalize";

export interface PhaseEvent {
  kind: "phase";
  phase: Phase;
}

export interface RpcRequest {
  id: string;
  method: string;
  params: unknown | null;
}

export interface RpcResponse {
  id: string;
  result: unknown | null;
  error: SerializedError | null;
}

export interface RunSummary {
  tablesMigrated: number;
  rowsMigrated: number;
  warningCount: number;
  elapsed: string;
}

export interface SerializedError {
  message: string;
  detail: string | null;
  stackTrace: string | null;
}

export interface TableEvent {
  kind: "table";
  table: string;
  rowsDone: number;
  rowsTotal: number | null;
  bytes: number;
}

export interface WarningEvent {
  kind: "warning";
  code: string;
  table: string | null;
  column: string | null;
  detail: string;
}

